name: Lint and Build

on:
  pull_request:
    branches: [ master ]
  push:
  release:
    types:
      - created

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          export PATH="$HOME/go/bin:$PATH"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Lint
        run: pre-commit run -a

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: sumnerevans
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install dependencies
        run: |
          nix-shell \
            --args forCI true \
            --command "Dependencies installed"

      - name: go build
        run: |
          nix-shell \
            --args forCI true \
            --command "go build -v ."

      - uses: actions/upload-artifact@v3
        with:
          name: sublime-music
          path: sublime-music-next
          if-no-files-found: error
