name: Lint and Build

on:
  pull_request:
    branches: [master]
  push:
  release:
    types:
      - created

env:
  GO_VERSION: 1.18

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          export PATH="$HOME/go/bin:$PATH"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev

      - run: make

      - uses: actions/upload-artifact@v3
        with:
          name: sublime-music
          path: sublime-music-next
          if-no-files-found: error
